### ISSUE TITLE
Can' build  mondrian from source .

### ISSUE THREAD

**Issue by air55555** [ojbc/mondrian-rest#12]
Can' build  mondrian from source as stated in build.md, that's why created this commit 
https://github.com/ojbc/mondrian/pull/1

**Comment by scottcame** [comment]
This is no longer necessary...just pushed version 1.4.3 of mondrian-rest that is dependent upon mondrian 4.7.0-21-184, which is available in the Pentaho nexus repos (see pom.xml for details).

Closed per 439ff0a
